#!/usr/bin/env bash

SCRIPT=$(cat <<-SCRIPTEND
#!/usr/bin/env bash

PORT=\$1

if [ -z \$PORT ]
then
  echo "Please specity a port number"
else
  PID=\$(lsof -ti :\$PORT)

  if [ -z "\$PID" ]
  then
          echo "Port \$PORT is already free"
  else
          kill \$PID
          echo "Port \$PORT is now free"
  fi
fi


SCRIPTEND
)

if ! command -v lsof > /dev/null
then
  echo "Command lsof not available..."
  if uname | grep "Linux" > /dev/null
  then
    echo "Linux distribution detected..."
    echo "Attempting to install lsof using apt-get..."
    sudo apt-get install lsof > /dev/null
    if command -v lsof > /dev/null
    then
      echo "Successfully installed lsof"
    fi
  fi
fi

touch /usr/local/bin/freeport
echo "$SCRIPT" > /usr/local/bin/freeport
chmod 755 /usr/local/bin/freeport

echo "Successfully installed freeport"
